name: flutter_ui_components
description: >-
  A Flutter UI kit with Material 3 theming, reusable widgets, utilities,
  shimmer loading, SVG icons, and light/dark theme support.
version: 0.0.1
homepage: https://github.com/VVK027/flutter_ui_components
repository: https://github.com/VVK027/flutter_ui_components
issue_tracker: https://github.com/VVK027/flutter_ui_components/issues

environment:
  sdk: ^3.10.9
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
